### ISSUE TITLE
Re-discovery and recovery?

### ISSUE THREAD

**Issue by clayvan** [jakubkulhan/ingress-merge#11]
So I'm just getting started but what happens in this scenario?

1. I create config map for merge.
2. I create some ingress objects that in turn create 1 "master" ingress object.
3. the ingress-merge controller pod gets restarted.
4. I want to update some of my "child" ingress objects

From what I can tell, the new ingress-merge controller does not know that it created the "master" ingress object and can't create a new one because of the name clash?
```
E0410 20:23:09.917300       1 controller.go:422] Could not create ingress [mynamespace/my-service]: ingresses.extensions "my-service" already exists
```

Am I using it wrong?

**Comment by jakubkulhan** [comment]
Hi @clayvan. In this case the controller should recognize that it created the ingress and do update instead. However, whether it may see existing ingress objects is affected by `--ingress-selector` command line option and RBAC rules. Do you use `--ingress-selector` option? Are RBAC rules set up properly?

**Comment by clayvan** [comment]
Ah bingo! That's what I was missing.

Although I was using --ingress-selector and the corresponding labels on my "child" ingress objects, and the configmap object itself, I did not include that label in my configmap to be inherited by the new "parent" ingress object.

```yaml
apiVersion: v1
kind: ConfigMap
metadata: 
  name: my-ingress-config
  namespace: default
  labels: 
    app: my-ingress
    merge.ingress.kubernetes.io: owned
data: 
  labels: |
    merge.ingress.kubernetes.io: owned
  annotations: |
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: my-arn
```

That way, when ingress-merge controller is restarted, it can re-discover the generated ingress.

Does that sound right to you?

Short follow up question, is the expectation to only run a single replica, or can ingress-merge handle having multiple? Is there any benefit?
