### ISSUE TITLE
ALB multiple certificates

### ISSUE THREAD

**Issue by hareku** [jakubkulhan/ingress-merge#2]
Hi
I want to use multiple certificates for ALB Ingress Controller. 
https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#ssl

I have to join `alb.ingress.kubernetes.io/certificate-arn` annotation with a comma.
Can ingress-merge do that?

**Comment by jakubkulhan** [comment]
@hareku Hi, ingress-merge doesn't merges/joins annotations from partial ingresses, instead you specify config map that contains annotations for resulting ingress:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: merged-ingress
data:
  annotations: |
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: ...certificates...
```
